### PR TITLE
Fix BTE_Move example and simplify #defines

### PR DESCRIPTION
**Pull request by MorganSandercock**
Just a few minor changes to remove "BTE" from the ROP constants and fix an error in the example that wasn't updated to the current name of the function.

### CODE REVIEW

**Comment by MorganSandercock** [comment]
BTE_Move() is fast! Really fast. Moving 32x40 pixel chars from layer 2 to layer 1, I measured well over 1400 chars per second. That's moving pixels at the rate of a few megapixels per second. The tens digits in my counter demo are just a blur and the hundreds move too fast to read.  The bottleneck is the Arduino - add a few integer divisions per loop and the update rate is halved.

**Comment by sumotoy** [comment]
BTEMoveMonochrome still not working as it should, I got garbage on 800x480, same as 272x480 on teensy. There's something missed, works on slow CPU but not fast one, probably a wait is missed.
I'm actually don't have time to look at, too busy at work and still try to code a font converter that it's a really big boy.
Btw I've updated the rest of function and changed again the name to reflect the other commands in BTE_move

**Comment by sumotoy** [comment]
BTEMoveMonochrome doesn't work at all at 8 bit, try it.

**Comment by MorganSandercock** [comment]
Yes, it works - it puts pixels on the screen. I got it working with small characters, like 8 pixels wide. I had to massage the data when writing the bitmap to the screen memory. (See code below.) For wider chars like 32 bits, I haven't solved the problems. There is one strip of the image which is affected by two locations on memory and one strip which never gets any pixels. It may be a bug in the way that the library writes colours in 8-bit mode. I haven't worked out why it always sends 16-bit colours even when in 8-bit mode. The 8-bit mode then throws away some of this information or writes it over adjacent memory locations which aren't displayed but are used by BTE_Move. (480x272 screen.)

  //copy the custom char onto the 2nd layer so it's stored onboard the RA8875
  tft.writeTo(L2);
  for(byte i=0;i<sizeof(battery1);i+=1) {
    if(tft.getColorBpp()==16) {
      tft.drawPixel(i*2, 0, battery1[i]);
    } else {
      //8-bit
      tft.drawPixel(i*2, 0, battery1[i]<<8);
    }      
  }

//draw the character to layer 1 at 30,190
tft.writeTo(L1);
tft.BTE_Move(0,0,8,16,30,190, 2, 1, true, 0x70, true);

**Comment by sumotoy** [comment]
I tested on a 800x480 but still garbage on screen, on the 272x480 works.

**Comment by sumotoy** [comment]
Definetively the BTEMoveMonochrome not working with 800x480 and any CPU, tried to figure out why but before all have to fix text rendering and digging trough code to find out bugs. I will reopen this when I figure out to solve this...

**Pull request closed without merging**
